// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

/**
 * @title ERC165Facet
 * @notice Autogenerated ABI-accurate stub facet (PayRox)
 * @dev Generated from ABI + selectors manifest; bodies intentionally revert.
 */
library ERC165FacetStorage {
    bytes32 internal constant SLOT = keccak256("payrox.facets.ERC165Facet.v1");
    struct Layout { uint256 __reserved; }
    function layout() internal pure returns (Layout storage l) { bytes32 p = SLOT; assembly { l.slot := p } }
}

contract ERC165Facet {
    function supportsInterface(bytes4 interfaceId) external view returns (bool ret0) {
        revert("TODO: migrate");
    }
}
