// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

/**
 * @title PauseFacet
 * @notice Autogenerated ABI-accurate stub facet (PayRox)
 * @dev Generated from ABI + selectors manifest; bodies intentionally revert.
 */
library PauseFacetStorage {
    bytes32 internal constant SLOT = keccak256("payrox.facets.PauseFacet.v1");
    struct Layout { uint256 __reserved; }
    function layout() internal pure returns (Layout storage l) { bytes32 p = SLOT; assembly { l.slot := p } }
}

contract PauseFacet {
    function unpause() external {
        revert("TODO: migrate");
    }

    function paused() external view returns (bool ret0) {
        revert("TODO: migrate");
    }

    function pause() external {
        revert("TODO: migrate");
    }
}
