// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

/**
 * @title PayRoxPaymentsFacet
 * @notice Autogenerated ABI-accurate stub facet (PayRox)
 * @dev Generated from ABI + selectors manifest; bodies intentionally revert.
 */
library PayRoxPaymentsFacetStorage {
    bytes32 internal constant SLOT = keccak256("payrox.facets.PayRoxPaymentsFacet.v1");
    struct Layout { uint256 __reserved; }
    function layout() internal pure returns (Layout storage l) { bytes32 p = SLOT; assembly { l.slot := p } }
}

contract PayRoxPaymentsFacet {
    function settlePayment(bytes32 ref) external {
        revert("TODO: migrate");
    }

    function createPayment(address to, uint256 amount, bytes32 ref) external payable {
        revert("TODO: migrate");
    }

    function getPayment(bytes32 ref) external view returns (address from, address to, uint256 amount, bool settled) {
        revert("TODO: migrate");
    }
}
