/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  PauseFacet,
  PauseFacetInterface,
} from "../../../contracts/facets/PauseFacet";

const _abi = [
  {
    inputs: [],
    name: "AlreadyPaused",
    type: "error",
  },
  {
    inputs: [],
    name: "NotPaused",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "NotPauser",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601557610230908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c80633f4ba83a1461012e5780635c975abb1461010057638456cb591461003a575f80fd5b346100fc575f3660031901126100fc57335f9081527ff72802865ab3e50a373d64e6c56f6982132f873f4500941f6a9b0373bcaadb5d602052604090205460ff16156100e9575f5160206101db5f395f51905f525460ff81166100da5760019060ff1916175f5160206101db5f395f51905f52557f62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a2586020604051338152a1005b631785c68160e01b5f5260045ffd5b6310351a3760e11b5f523360045260245ffd5b5f80fd5b346100fc575f3660031901126100fc57602060ff5f5160206101db5f395f51905f5254166040519015158152f35b346100fc575f3660031901126100fc57335f9081527ff72802865ab3e50a373d64e6c56f6982132f873f4500941f6a9b0373bcaadb5d602052604090205460ff16156100e9575f5160206101db5f395f51905f525460ff8116156101cb5760ff19165f5160206101db5f395f51905f52557f5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa6020604051338152a1005b636cd6020160e01b5f5260045ffdfe9b02e42a9b92e93607133334d133e31dc3f904c7156cf846526371c09ab4c5b2a2646970667358221220d6821c887b83738ca518966e409594fa68727c6a780f2e44e972b9cabc5c072364736f6c634300081e0033";

type PauseFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PauseFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PauseFacet__factory extends ContractFactory {
  constructor(...args: PauseFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PauseFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PauseFacet__factory {
    return super.connect(runner) as PauseFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PauseFacetInterface {
    return new Interface(_abi) as PauseFacetInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PauseFacet {
    return new Contract(address, _abi, runner) as unknown as PauseFacet;
  }
}
