/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAntiBot } from "./IAntiBot";
export type { IChunkFactory } from "./IChunkFactory";
export type { IDiamondLoupe } from "./IDiamondLoupe";
export type { IDiamondLoupeEx } from "./IDiamondLoupeEx";
export type { IManifestDispatcher } from "./IManifestDispatcher";
export type { ISaltView } from "./ISaltView";
