/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAntiBot,
  IAntiBotInterface,
} from "../../../contracts/interfaces/IAntiBot";

const _abi = [
  {
    inputs: [],
    name: "checkPriceImpact",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "commitWhitelistAdd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hashedData",
        type: "bytes32",
      },
    ],
    name: "createCommit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
    ],
    name: "emergencyPriceOverride",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "executeCommit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "voteToActivateFailsafeMode",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "voteToDeactivateFailsafeMode",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAntiBot__factory {
  static readonly abi = _abi;
  static createInterface(): IAntiBotInterface {
    return new Interface(_abi) as IAntiBotInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAntiBot {
    return new Contract(address, _abi, runner) as unknown as IAntiBot;
  }
}
