name: Quality Gates

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Compile contracts
        run: npx hardhat compile

      - name: 🔗 Wiring / manifest parity check
        run: npm run check:wire

      # Note: TypeScript check temporarily disabled due to untracked cross-chain files pending curation
      # - name: Build (type check only)
      #   run: npm run check:ts

      - name: Strict Lint
        run: npm run lint

      - name: Zero Issue Lint (baseline gate)
        run: npm run lint:zero

      - name: Tests (core diamond integrity subset)
        run: npm run test:integrity

      - name: Integration wiring test
        run: npx hardhat test --grep "wiring"

      - name: Summaries
        if: always()
        run: |
          echo 'Baseline messages:'
          cat .quality/lint-zero-baseline.json || true
