name: 'Ultra-Clean CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  minimal-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies (ignore audit)
        run: npm install --no-audit --no-fund
        
      - name: Test basic Node.js functionality
        run: node --version
        
      - name: Success
        run: echo "✅ Ultra-clean repository CI passed"
